### ISSUE TITLE
Running this on a kubernetes cluster

### ISSUE THREAD

**Issue by craigwillis85** [tech-angels/docker-fluentd-kubernetes-gelf#2]
Hi

I'm looking at using this to export some logs to an external graylog server I have setup (uses gelf).

I was wondering how I would use this in k8s to export the logs?

Would it be a DaemonSet, Job, Deployment?

Any help, or an example manifest would be much appreciated

**Comment by groulot** [comment]
Hello,

we used a manifest to do it, we use openshift and it's located at "./origin/node/openshift.local.manifests/logging.yaml" but with Kubernetes it's in /etc/kubernetes/manifests (this page explains how to do it : http://logz.io/blog/kubernetes-log-analysis/ )

Here's our file:
apiVersion: v1
kind: Pod
metadata:
  name: fluentd-graylog
spec:
  containers:
- name: fluentd-graylog
  image: groulot/docker-fluentd-kubernetes-gelf
  securityContext:
    privileged: true
  resources:
    limits:
      cpu: 100m
  volumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
    env:
  - name: "GELF_HOST"
    value: "192.168.1.100"
  - name: "GELF_PORT"
    value: "1515"
    volumes:
- name: varlog
  hostPath:
    path: /var/log
- name: varlibdockercontainers
  hostPath:
    path: /var/lib/docker/containers

I hope that helps, there's probably better ways to run this now but we didn't look into them as this fits our needs.
