### ISSUE TITLE
Publish to Docker Hub

### ISSUE THREAD

**Issue by FrederikNJS** [tech-angels/docker-fluentd-kubernetes-gelf#3]
This image is just what I need!
Would it be possible for you to deploy the image (maybe even automated) to the official Docker Hub?

**Comment by gravis** [comment]
There you go :)
https://hub.docker.com/r/techangels/docker-fluentd-kubernetes-gelf/tags/

**Comment by FrederikNJS** [comment]
Brilliant, thanks!
